FROM httpd:2.4
COPY ./httpd.conf /usr/local/apache2/conf/httpd.conf
COPY ./passwords /usr/local/apache2/conf/passwords
COPY ./login.html /usr/local/apache2/htdocs/login.html
COPY ./index.html /usr/local/apache2/htdocs/index.html